import { ATTACK_TYPES } from "./moves"

export const allMovesMoveset = ATTACK_TYPES.map((attack) => attack.name)

export const defaultMoveset = [
  "Punch",
  "Punch (High Combo Chance)",
  "Kick",
  "Kick (High Combo Chance)",
  "Ki Blast",
  "Ki Blast(High Combo Chance)",
  "Ki Channeling",
  "Dodge",
  "Block",
  "Nothing",
  "Skip My Turn",
  "Surrender",
]

export const commonMoveset = [
  "Punch",
  "Punch (High Combo Chance)",
  "Kick",
  "Kick (High Combo Chance)",
  "Elbow",
  "Knee",
  "Shoulder Ram",
  "Shin Kick",
  "Uppercut",
  "Ki Blast",
  "Ki Blast(High Combo Chance)",
  "Signature Technique lvl1",
  "Dodge",
  "Block",
  "Nothing",
  "Ki Channeling",
  "Skip My Turn",
  "Surrender",
]

export const commonMoveset_Android = [
  "Punch",
  "Punch (High Combo Chance)",
  "Kick",
  "Kick (High Combo Chance)",
  "Elbow",
  "Knee",
  "Shoulder Ram",
  "Shin Kick",
  "Uppercut",
  "Ki Blast",
  "Ki Blast(High Combo Chance)",
  "Signature Technique lvl1",
  "Dodge",
  "Block",
  "Nothing",
  "Ki Absorb",
  "Hikou Flight",
  "Skip My Turn",
  "Surrender",
]

export const commonMoveset_Duugo = [
  "Punch",
  "Punch (High Combo Chance)",
  "Kick",
  "Kick (High Combo Chance)",
  "Elbow",
  "Knee",
  "Shoulder Ram",
  "Shin Kick",
  "Uppercut",
  "Duugo Tail Whip",
  "Ki Blast",
  "Ki Blast(High Combo Chance)",
  "Signature Technique lvl1",
  "Dodge",
  "Block",
  "Nothing",
  "Ki Channeling",
  "Skip My Turn",
  "Surrender",
]

export const spaceWarriorMoveset = [
  "Punch",
  "Punch (High Combo Chance)",
  "Kick",
  "Kick (High Combo Chance)",
  "Elbow",
  "Knee",
  "Shoulder Ram",
  "Shin Kick",
  "Uppercut",
  "Ki Blast",
  "Ki Blast(High Combo Chance)",
  "Dodge",
  "Block",
  "Nothing",
  "Space Ki Gun", //Ki guns are like Ki Blasts, but do slightly less damage. 30 ki bullets.
  "Flight",
  "Ki Channeling",
  "Skip My Turn",
  "Surrender",
]

export const defaultMoveset_Android = [
  "Punch",
  "Punch (High Combo Chance)",
  "Kick",
  "Kick (High Combo Chance)",
  "Ki Blast",
  "Ki Blast(High Combo Chance)",
  "Dodge",
  "Block",
  "Ki Absorb",
  "Nothing",
  "Hikou Flight",
  "Skip My Turn",
  "Surrender",
]

export const defaultMoveset_Duugo = [
  "Punch",
  "Punch (High Combo Chance)",
  "Kick",
  "Kick (High Combo Chance)",
  "Duugo Tail Whip",
  "Ki Blast",
  "Ki Blast(High Combo Chance)",
  "Dodge",
  "Block",
  "Nothing",
  "Ki Channeling",
  "Skip My Turn",
  "Surrender",
]

export const SeiferBladesMoveset = [
  "Punch",
  "Punch (High Combo Chance)",
  "Kick",
  "Kick (High Combo Chance)",
  "Elbow",
  "Knee",
  "Shoulder Ram",
  "Shin Kick",
  "Uppercut",
  "Signature Technique lvl1",
  "Medium Saiyan Armor",
  "Masenko",
  "Brass Knuckles",
  "Ki Blast",
  "Ki Blast(High Combo Chance)",
  "Dodge",
  "Block",
  "Ki Absorb",
  "Nothing",
  "Hikou Flight",
  "JiuJitsu (White Belt)",
  "Skip My Turn",
  "Surrender",
]

export const spaceWarriorMoveset_Strong = [
  "Punch",
  "Punch (High Combo Chance)",
  "Kick",
  "Kick (High Combo Chance)",
  "Elbow",
  "Knee",
  "Shoulder Ram",
  "Shin Kick",
  "Uppercut",
  "Ki Blast",
  "Ki Blast(High Combo Chance)",
  "lvl 3 Guard Crush",
  "Dodge",
  "Block",
  "Nothing",
  "Space Ki Gun",
  "Ki Channeling",
  "Flight",
  "Skip My Turn",
  "Surrender",
]

